#!/bin/sh

# This script destroys the database then rebuilds it and imports the data.

if [ -z "$1" ]
  then
	PROPERTIES=""
  else
    PROPERTIES=$@
fi

echo "Destroying existing database"
mvn install -DskipTests=true -Pdestroy-db $@
echo "Creating new database"
mvn install -DskipTests=true -Pcreate-db $@
echo "Altering database schema"
mvn install -DskipTests=true -Pupdate-db $@
echo "Importing data into database"
mvn install -DskipTests=true -Ppopulate-db $@

